[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 100.64.0.0/10 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 51.255.43.100

[sshd]
enabled = true
maxretry = 4
findtime = 10m
bantime = 1h

[reciapp-probes]
enabled = true
filter = reciapp-probes
backend = auto
logpath = /data/coolify/proxy/access.log
maxretry = 8
findtime = 10m
bantime = 1h
port = http,https
banaction = nftables[type=allports]

[recidive]
enabled = false
