from __future__ import annotations

from app.localization import SUPPORTED_LANGUAGE_CODES, normalize_language

# Canonical English messages stored on jobs / raised as ExtractError.
RECIPE_UNDETERMINED = "Could not determine a recipe from this video."
RECIPE_INCOMPLETE = "Could not extract a complete recipe from this video."
RECIPE_NO_INGREDIENTS = "This video is missing a clear ingredient list."
RECIPE_NO_METHOD = "This video is missing clear cooking steps."
LINK_IN_BIO = "Recipe link in bio. Open the creator profile bio for the full recipe."
UNSUPPORTED_URL = "Unsupported URL. Use TikTok, YouTube, Instagram or Facebook."
VIDEO_TOO_LONG = "This video is too long to extract a recipe."
INCOMPLETE_CAROUSEL = "This TikTok carousel is incomplete. Try another link or a full recipe video."
EXTRACTION_RETRYABLE = "Extraction temporarily failed. Retry the import."
NO_RECIPE_TEXT = "No usable recipe text found in this video."
SOURCE_BOUND = "This recipe source is too large to process."
STALE_JOB = "Job expired before completion. Retry the import."
TRANSLATION_MISSING = "Recipe not found for translation."

# Stable codes for tests / clients that want to branch without parsing copy.
ERROR_CODES: dict[str, str] = {
    RECIPE_UNDETERMINED: "recipe_undetermined",
    RECIPE_INCOMPLETE: "recipe_incomplete",
    RECIPE_NO_INGREDIENTS: "recipe_no_ingredients",
    RECIPE_NO_METHOD: "recipe_no_method",
    LINK_IN_BIO: "link_in_bio",
    UNSUPPORTED_URL: "unsupported_url",
    VIDEO_TOO_LONG: "video_too_long",
    INCOMPLETE_CAROUSEL: "incomplete_carousel",
    EXTRACTION_RETRYABLE: "extraction_retryable",
    NO_RECIPE_TEXT: "no_recipe_text",
    SOURCE_BOUND: "source_bound",
    STALE_JOB: "stale_job",
    TRANSLATION_MISSING: "translation_missing",
}

_MESSAGES: dict[str, dict[str, str]] = {
    RECIPE_UNDETERMINED: {
        "ar": "تعذر التعرف على وصفة من هذا الفيديو.",
        "bn": "এই ভিডিও থেকে রেসিপি নির্ধারণ করা যায়নি।",
        "ca": "No s'ha pogut determinar una recepta d'aquest vídeo.",
        "zh-Hans": "无法从此视频识别出食谱。",
        "zh-Hant": "無法從此影片識別出食譜。",
        "hr": "Nije moguće odrediti recept iz ovog videa.",
        "cs": "Z tohoto videa se nepodařilo určit recept.",
        "da": "Kunne ikke finde en opskrift i denne video.",
        "nl": "Kon geen recept uit deze video bepalen.",
        "en-AU": RECIPE_UNDETERMINED,
        "en-CA": RECIPE_UNDETERMINED,
        "en-GB": RECIPE_UNDETERMINED,
        "en-US": RECIPE_UNDETERMINED,
        "fi": "Tästä videosta ei voitu tunnistaa reseptiä.",
        "fr-FR": "Impossible de reconnaître une recette dans cette vidéo.",
        "fr-CA": "Impossible de reconnaître une recette dans cette vidéo.",
        "de": "Aus diesem Video konnte kein Rezept erkannt werden.",
        "el": "Δεν ήταν δυνατός ο εντοπισμός συνταγής σε αυτό το βίντεο.",
        "gu": "આ વીડિયામાંથી રેસીપી નક્કી કરી શકાઈ નથી.",
        "he": "לא ניתן היה לזהות מתכון מהסרטון הזה.",
        "hi": "इस वीडियो से रेसिपी पहचानी नहीं जा सकी।",
        "hu": "Nem sikerült receptet felismerni ebből a videóból.",
        "id": "Tidak dapat menentukan resep dari video ini.",
        "it": "Impossibile riconoscere una ricetta in questo video.",
        "ja": "この動画からレシピを特定できませんでした。",
        "kn": "ಈ ವೀಡಿಯೊದಿಂದ ರೆಸಿಪಿ ನಿರ್ಧರಿಸಲಾಗಲಿಲ್ಲ.",
        "ko": "이 영상에서 레시피를 확인할 수 없습니다.",
        "ms": "Tidak dapat menentukan resipi daripada video ini.",
        "ml": "ഈ വീഡിയോയിൽ നിന്ന് പാചകക്കുറിപ്പ് കണ്ടെത്താനായില്ല.",
        "mr": "या व्हिडिओतून रेसिपी ओळखता आली नाही.",
        "nb": "Kunne ikke finne en oppskrift i denne videoen.",
        "or": "ଏହି ଭିଡିଓରୁ ରେସିପି ନିର୍ଣ୍ଣୟ କରାଯାଇପାରିଲା ନାହିଁ।",
        "pl": "Nie udało się rozpoznać przepisu w tym filmie.",
        "pt-BR": "Não foi possível reconhecer uma receita neste vídeo.",
        "pt-PT": "Não foi possível reconhecer uma receita neste vídeo.",
        "pa": "ਇਸ ਵੀਡੀਓ ਤੋਂ ਰੈਸਿਪੀ ਪਛਾਣੀ ਨਹੀਂ ਜਾ ਸਕੀ।",
        "ro": "Nu s-a putut determina o rețetă din acest video.",
        "ru": "Не удалось определить рецепт в этом видео.",
        "sk": "Z tohto videa sa nepodarilo určiť recept.",
        "sl": "Iz tega videoposnetka ni bilo mogoče določiti recepta.",
        "es-MX": "No se pudo reconocer una receta en este video.",
        "es-ES": "No se pudo reconocer una receta en este vídeo.",
        "sv": "Kunde inte avgöra ett recept från den här videon.",
        "ta": "இந்த வீடியோவிலிருந்து செய்முறையை அறிய முடியவில்லை.",
        "te": "ఈ వీడియో నుండి రెసిపీని గుర్తించలేకపోయాం.",
        "th": "ไม่สามารถระบุสูตรจากวิดีโอนี้ได้",
        "tr": "Bu videodan bir tarif belirlenemedi.",
        "uk": "Не вдалося визначити рецепт із цього відео.",
        "ur": "اس ویڈیو سے ترکیب معلوم نہیں ہو سکی۔",
        "vi": "Không thể xác định công thức từ video này.",
    },
    RECIPE_INCOMPLETE: {
        "ar": "تعذر استخراج وصفة كاملة من هذا الفيديو.",
        "bn": "এই ভিডিও থেকে সম্পূর্ণ রেসিপি বের করা যায়নি।",
        "ca": "No s'ha pogut extreure una recepta completa d'aquest vídeo.",
        "zh-Hans": "无法从此视频提取完整食谱。",
        "zh-Hant": "無法從此影片擷取完整食譜。",
        "hr": "Nije moguće izvući potpuni recept iz ovog videa.",
        "cs": "Z tohoto videa se nepodařilo získat kompletní recept.",
        "da": "Kunne ikke hente en komplet opskrift fra denne video.",
        "nl": "Kon geen volledig recept uit deze video halen.",
        "en-AU": RECIPE_INCOMPLETE,
        "en-CA": RECIPE_INCOMPLETE,
        "en-GB": RECIPE_INCOMPLETE,
        "en-US": RECIPE_INCOMPLETE,
        "fi": "Tästä videosta ei voitu poimia täydellistä reseptiä.",
        "fr-FR": "Impossible d'extraire une recette complète de cette vidéo.",
        "fr-CA": "Impossible d'extraire une recette complète de cette vidéo.",
        "de": "Aus diesem Video konnte kein vollständiges Rezept extrahiert werden.",
        "el": "Δεν ήταν δυνατή η εξαγωγή πλήρους συνταγής από αυτό το βίντεο.",
        "gu": "આ વીડિયામાંથી સંપૂર્ણ રેસીપી કાઢી શકાઈ નથી.",
        "he": "לא ניתן היה לחלץ מתכון מלא מהסרטון הזה.",
        "hi": "इस वीडियो से पूरी रेसिपी निकाल नहीं पाए।",
        "hu": "Nem sikerült teljes receptet kinyerni ebből a videóból.",
        "id": "Tidak dapat mengekstrak resep lengkap dari video ini.",
        "it": "Impossibile estrarre una ricetta completa da questo video.",
        "ja": "この動画から完全なレシピを抽出できませんでした。",
        "kn": "ಈ ವೀಡಿಯೊದಿಂದ ಸಂಪೂರ್ಣ ರೆಸಿಪಿ ಹೊರತೆಗೆಯಲಾಗಲಿಲ್ಲ.",
        "ko": "이 영상에서 완전한 레시피를 추출할 수 없습니다.",
        "ms": "Tidak dapat mengekstrak resipi lengkap daripada video ini.",
        "ml": "ഈ വീഡിയോയിൽ നിന്ന് പൂർണ്ണമായ പാചകക്കുറിപ്പ് എടുക്കാനായില്ല.",
        "mr": "या व्हिडिओतून पूर्ण रेसिपी काढता आली नाही.",
        "nb": "Kunne ikke hente en komplett oppskrift fra denne videoen.",
        "or": "ଏହି ଭିଡିଓରୁ ସମ୍ପୂର୍ଣ୍ଣ ରେସିପି ବାହାର କରାଯାଇପାରିଲା ନାହିଁ।",
        "pl": "Nie udało się wyodrębnić pełnego przepisu z tego filmu.",
        "pt-BR": "Não foi possível extrair uma receita completa deste vídeo.",
        "pt-PT": "Não foi possível extrair uma receita completa deste vídeo.",
        "pa": "ਇਸ ਵੀਡੀਓ ਤੋਂ ਪੂਰੀ ਰੈਸਿਪੀ ਕੱਢ ਨਹੀਂ ਸਕੇ।",
        "ro": "Nu s-a putut extrage o rețetă completă din acest video.",
        "ru": "Не удалось извлечь полный рецепт из этого видео.",
        "sk": "Z tohto videa sa nepodarilo získať kompletný recept.",
        "sl": "Iz tega videoposnetka ni bilo mogoče izluščiti celotnega recepta.",
        "es-MX": "No se pudo extraer una receta completa de este video.",
        "es-ES": "No se pudo extraer una receta completa de este vídeo.",
        "sv": "Kunde inte hämta ett komplett recept från den här videon.",
        "ta": "இந்த வீடியோவிலிருந்து முழு செய்முறையை எடுக்க முடியவில்லை.",
        "te": "ఈ వీడియో నుండి పూర్తి రెసిపీని తీయలేకపోయాం.",
        "th": "ไม่สามารถดึงสูตรครบถ้วนจากวิดีโอนี้ได้",
        "tr": "Bu videodan eksiksiz bir tarif çıkarılamadı.",
        "uk": "Не вдалося витягти повний рецепт із цього відео.",
        "ur": "اس ویڈیو سے مکمل ترکیب نہیں نکال سکتے۔",
        "vi": "Không thể trích xuất công thức đầy đủ từ video này.",
    },
    RECIPE_NO_INGREDIENTS: {
        "ar": "هذا الفيديو لا يتضمن قائمة مكونات واضحة.",
        "bn": "এই ভিডিওতে স্পষ্ট উপকরণের তালিকা নেই।",
        "ca": "Aquest vídeo no inclou una llista clara d'ingredients.",
        "zh-Hans": "这个视频没有清晰的食材清单。",
        "zh-Hant": "這個影片沒有清楚的食材清單。",
        "hr": "Ovaj video nema jasan popis sastojaka.",
        "cs": "Toto video neobsahuje jasný seznam surovin.",
        "da": "Denne video mangler en tydelig ingrediensliste.",
        "nl": "Deze video mist een duidelijke ingrediëntenlijst.",
        "en-AU": RECIPE_NO_INGREDIENTS,
        "en-CA": RECIPE_NO_INGREDIENTS,
        "en-GB": RECIPE_NO_INGREDIENTS,
        "en-US": RECIPE_NO_INGREDIENTS,
        "fi": "Tästä videosta puuttuu selkeä ainesluettelo.",
        "fr-FR": "Cette vidéo n'inclut pas de liste d'ingrédients claire.",
        "fr-CA": "Cette vidéo n'inclut pas de liste d'ingrédients claire.",
        "de": "In diesem Video fehlt eine klare Zutatenliste.",
        "el": "Αυτό το βίντεο δεν περιλαμβάνει σαφή λίστα υλικών.",
        "gu": "આ વીડિયામાં સ્પષ્ટ ઘટકોની યાદી નથી.",
        "he": "בסרטון הזה אין רשימת מרכיבים ברורה.",
        "hi": "इस वीडियो में सामग्री की स्पष्ट सूची नहीं है।",
        "hu": "Ebben a videóban nincs egyértelmű hozzávalólista.",
        "id": "Video ini tidak memiliki daftar bahan yang jelas.",
        "it": "Questo video non include un elenco chiaro di ingredienti.",
        "ja": "この動画には明確な材料リストがありません。",
        "kn": "ಈ ವೀಡಿಯೊದಲ್ಲಿ ಸ್ಪಷ್ಟ ಪದಾರ್ಥಗಳ ಪಟ್ಟಿ ಇಲ್ಲ.",
        "ko": "이 영상에는 명확한 재료 목록이 없습니다.",
        "ms": "Video ini tiada senarai bahan yang jelas.",
        "ml": "ഈ വീഡിയോയിൽ വ്യക്തമായ ചേരുവകളുടെ പട്ടികയില്ല.",
        "mr": "या व्हिडिओमध्ये स्पष्ट साहित्य यादी नाही.",
        "nb": "Denne videoen mangler en tydelig ingrediensliste.",
        "or": "ଏହି ଭିଡିଓରେ ସ୍ପଷ୍ଟ ଉପାଦାନ ତାଲିକା ନାହିଁ।",
        "pl": "W tym filmie brakuje wyraźnej listy składników.",
        "pt-BR": "Este vídeo não inclui uma lista clara de ingredientes.",
        "pt-PT": "Este vídeo não inclui uma lista clara de ingredientes.",
        "pa": "ਇਸ ਵੀਡੀਓ ਵਿੱਚ ਸਮੱਗਰੀ ਦੀ ਸਪਸ਼ਟ ਸੂਚੀ ਨਹੀਂ ਹੈ।",
        "ro": "Acest video nu include o listă clară de ingrediente.",
        "ru": "В этом видео нет понятного списка ингредиентов.",
        "sk": "Toto video neobsahuje jasný zoznam surovín.",
        "sl": "Ta videoposnetek nima jasnega seznama sestavin.",
        "es-MX": "Este video no incluye una lista clara de ingredientes.",
        "es-ES": "Este vídeo no incluye una lista clara de ingredientes.",
        "sv": "Den här videon saknar en tydlig ingredienslista.",
        "ta": "இந்த வீடியோவில் தெளிவான பொருட்கள் பட்டியல் இல்லை.",
        "te": "ఈ వీడియోలో స్పష్టమైన పదార్థాల జాబితా లేదు.",
        "th": "วิดีโอนี้ไม่มีรายการส่วนผสมที่ชัดเจน",
        "tr": "Bu videoda net bir malzeme listesi yok.",
        "uk": "У цьому відео немає чіткого списку інгредієнтів.",
        "ur": "اس ویڈیو میں اجزاء کی واضح فہرست نہیں ہے۔",
        "vi": "Video này thiếu danh sách nguyên liệu rõ ràng.",
    },
    RECIPE_NO_METHOD: {
        "ar": "هذا الفيديو لا يتضمن خطوات تحضير واضحة.",
        "bn": "এই ভিডিওতে রান্নার স্পষ্ট ধাপ নেই।",
        "ca": "Aquest vídeo no inclou passos de cocció clars.",
        "zh-Hans": "这个视频没有清晰的烹饪步骤。",
        "zh-Hant": "這個影片沒有清楚的烹飪步驟。",
        "hr": "Ovaj video nema jasne korake pripreme.",
        "cs": "Toto video neobsahuje jasné postupy přípravy.",
        "da": "Denne video mangler tydelige tilberedningstrin.",
        "nl": "Deze video mist duidelijke bereidingsstappen.",
        "en-AU": RECIPE_NO_METHOD,
        "en-CA": RECIPE_NO_METHOD,
        "en-GB": RECIPE_NO_METHOD,
        "en-US": RECIPE_NO_METHOD,
        "fi": "Tästä videosta puuttuvat selkeät valmistusohjeet.",
        "fr-FR": "Cette vidéo n'inclut pas d'étapes de préparation claires.",
        "fr-CA": "Cette vidéo n'inclut pas d'étapes de préparation claires.",
        "de": "In diesem Video fehlen klare Zubereitungsschritte.",
        "el": "Αυτό το βίντεο δεν περιλαμβάνει σαφή βήματα μαγειρέματος.",
        "gu": "આ વીડિયામાં રસોઈના સ્પષ્ટ પગલાં નથી.",
        "he": "בסרטון הזה אין שלבי הכנה ברורים.",
        "hi": "इस वीडियो में पकाने के स्पष्ट चरण नहीं हैं।",
        "hu": "Ebben a videóban nincsenek egyértelmű elkészítési lépések.",
        "id": "Video ini tidak memiliki langkah memasak yang jelas.",
        "it": "Questo video non include passaggi di cottura chiari.",
        "ja": "この動画には明確な作り方の手順がありません。",
        "kn": "ಈ ವೀಡಿಯೊದಲ್ಲಿ ಸ್ಪಷ್ಟ ಅಡುಗೆ ಹಂತಗಳಿಲ್ಲ.",
        "ko": "이 영상에는 명확한 조리 단계가 없습니다.",
        "ms": "Video ini tiada langkah memasak yang jelas.",
        "ml": "ഈ വീഡിയോയിൽ വ്യക്തമായ പാചക ഘട്ടങ്ങളില്ല.",
        "mr": "या व्हिडिओमध्ये स्वयंपाकाचे स्पष्ट टप्पे नाहीत.",
        "nb": "Denne videoen mangler tydelige tilberedningstrinn.",
        "or": "ଏହି ଭିଡିଓରେ ରୋଷେଇର ସ୍ପଷ୍ଟ ପଦକ୍ଷେପ ନାହିଁ।",
        "pl": "W tym filmie brakuje wyraźnych kroków przygotowania.",
        "pt-BR": "Este vídeo não inclui etapas de preparo claras.",
        "pt-PT": "Este vídeo não inclui passos de preparação claros.",
        "pa": "ਇਸ ਵੀਡੀਓ ਵਿੱਚ ਪਕਾਉਣ ਦੇ ਸਪਸ਼ਟ ਕਦਮ ਨਹੀਂ ਹਨ।",
        "ro": "Acest video nu include pași clari de preparare.",
        "ru": "В этом видео нет понятных шагов приготовления.",
        "sk": "Toto video neobsahuje jasné kroky prípravy.",
        "sl": "Ta videoposnetek nima jasnih korakov priprave.",
        "es-MX": "Este video no incluye pasos de cocción claros.",
        "es-ES": "Este vídeo no incluye pasos de cocción claros.",
        "sv": "Den här videon saknar tydliga tillagningssteg.",
        "ta": "இந்த வீடியோவில் தெளிவான சமையல் படிகள் இல்லை.",
        "te": "ఈ వీడియోలో స్పష్టమైన వంట దశలు లేవు.",
        "th": "วิดีโอนี้ไม่มีขั้นตอนการทำอาหารที่ชัดเจน",
        "tr": "Bu videoda net pişirme adımları yok.",
        "uk": "У цьому відео немає чітких кроків приготування.",
        "ur": "اس ویڈیو میں پکانے کے واضح مراحل نہیں ہیں۔",
        "vi": "Video này thiếu các bước nấu rõ ràng.",
    },
    LINK_IN_BIO: {
        "ar": "رابط الوصفة في البايو. افتح ملف المنشئ للاطلاع على الوصفة الكاملة.",
        "bn": "রেসিপির লিংক বায়োতে আছে। সম্পূর্ণ রেসিপির জন্য ক্রিয়েটরের প্রোফাইল দেখুন।",
        "ca": "L'enllaç de la recepta és al bio. Obre el perfil del creador per a la recepta completa.",
        "zh-Hans": "完整食谱在简介链接中。请打开创作者主页查看。",
        "zh-Hant": "完整食譜在簡介連結中。請打開創作者主頁查看。",
        "hr": "Link recepta je u bio. Otvori profil kreatora za cijeli recept.",
        "cs": "Odkaz na recept je v bio. Otevřete profil tvůrce pro celý recept.",
        "da": "Opskriftslinket er i bio. Åbn skaberens profil for den fulde opskrift.",
        "nl": "Receptlink staat in de bio. Open het profiel van de maker voor het volledige recept.",
        "en-AU": LINK_IN_BIO,
        "en-CA": LINK_IN_BIO,
        "en-GB": LINK_IN_BIO,
        "en-US": LINK_IN_BIO,
        "fi": "Reseptilinkki on biossa. Avaa tekijän profiili saadaksesi koko reseptin.",
        "fr-FR": "Le lien de la recette est dans la bio. Ouvrez le profil du créateur pour la recette complète.",
        "fr-CA": "Le lien de la recette est dans la bio. Ouvrez le profil du créateur pour la recette complète.",
        "de": "Rezeptlink in der Bio. Öffne das Creator-Profil für das vollständige Rezept.",
        "el": "Ο σύνδεσμος της συνταγής είναι στο bio. Άνοιξε το προφίλ του δημιουργού για την πλήρη συνταγή.",
        "gu": "રેસીપીની લિંક બાયોમાં છે. સંપૂર્ણ રેસીપી માટે ક્રિએટરની પ્રોફાઇલ ખોલો.",
        "he": "קישור למתכון נמצא בביו. פתח את פרופיל היוצר למתכון המלא.",
        "hi": "रेसिपी का लिंक बायो में है। पूरी रेसिपी के लिए क्रिएटर की प्रोफ़ाइल खोलें।",
        "hu": "A recept linkje a bióban van. Nyisd meg az alkotó profilját a teljes receptért.",
        "id": "Tautan resep ada di bio. Buka profil kreator untuk resep lengkap.",
        "it": "Il link della ricetta è in bio. Apri il profilo del creator per la ricetta completa.",
        "ja": "レシピのリンクはプロフィールにあります。作成者のプロフィールを開いてください。",
        "kn": "ರೆಸಿಪಿ ಲಿಂಕ್ ಬಯೋದಲ್ಲಿದೆ. ಪೂರ್ಣ ರೆಸಿಪಿಗಾಗಿ ಕ್ರಿಯೇಟರ್ ಪ್ರೊಫೈಲ್ ತೆರೆಯಿರಿ.",
        "ko": "레시피 링크가 소개에 있습니다. 전체 레시피는 크리에이터 프로필에서 확인하세요.",
        "ms": "Pautan resipi ada dalam bio. Buka profil pencipta untuk resipi penuh.",
        "ml": "പാചകക്കുറിപ്പ് ലിങ്ക് ബയോയിലുണ്ട്. പൂർണ്ണ പാചകക്കുറിപ്പിന് ക്രിയേറ്റർ പ്രൊഫൈൽ തുറക്കുക.",
        "mr": "रेसिपीची लिंक बायोमध्ये आहे. पूर्ण रेसिपीसाठी क्रिएटर प्रोफाइल उघडा.",
        "nb": "Oppskriftslenken er i bio. Åpne skaperens profil for hele oppskriften.",
        "or": "ରେସିପି ଲିଙ୍କ୍ ବାୟୋରେ ଅଛି। ସମ୍ପୂର୍ଣ୍ଣ ରେସିପି ପାଇଁ କ୍ରିଏଟର ପ୍ରୋଫାଇଲ୍ ଖୋଲନ୍ତୁ।",
        "pl": "Link do przepisu jest w bio. Otwórz profil twórcy, aby zobaczyć cały przepis.",
        "pt-BR": "O link da receita está na bio. Abra o perfil do criador para a receita completa.",
        "pt-PT": "A ligação da receita está na bio. Abra o perfil do criador para a receita completa.",
        "pa": "ਰੈਸਿਪੀ ਲਿੰਕ ਬਾਇਓ ਵਿੱਚ ਹੈ। ਪੂਰੀ ਰੈਸਿਪੀ ਲਈ ਕ੍ਰੀਏਟਰ ਪ੍ਰੋਫਾਈਲ ਖੋਲ੍ਹੋ।",
        "ro": "Linkul rețetei este în bio. Deschide profilul creatorului pentru rețeta completă.",
        "ru": "Ссылка на рецепт в био. Откройте профиль автора, чтобы увидеть полный рецепт.",
        "sk": "Odkaz na recept je v bio. Otvorte profil tvorcu pre celý recept.",
        "sl": "Povezava do recepta je v bio. Odprite profil ustvarjalca za celoten recept.",
        "es-MX": "El enlace de la receta está en el bio. Abre el perfil del creador para verla completa.",
        "es-ES": "El enlace de la receta está en el bio. Abre el perfil del creador para verla completa.",
        "sv": "Receptlänken finns i bio. Öppna skaparens profil för hela receptet.",
        "ta": "செய்முறை இணைப்பு பயோவில் உள்ளது. முழு செய்முறைக்கு உருவாக்குநர் சுயவிவரத்தைத் திறக்கவும்.",
        "te": "రెసిపీ లింక్ బయోలో ఉంది. పూర్తి రెసిపీకి క్రియేటర్ ప్రొఫైల్ తెరవండి.",
        "th": "ลิงก์สูตรอยู่ในไบโอ เปิดโปรไฟล์ครีเอเตอร์เพื่อดูสูตรเต็ม",
        "tr": "Tarif bağlantısı biyoda. Tam tarif için içerik üreticisinin profilini açın.",
        "uk": "Посилання на рецепт у біо. Відкрийте профіль автора, щоб побачити повний рецепт.",
        "ur": "ترکیب کا لنک بائیو میں ہے۔ مکمل ترکیب کے لیے کریئیٹر پروفائل کھولیں۔",
        "vi": "Liên kết công thức nằm trong bio. Mở hồ sơ người tạo để xem công thức đầy đủ.",
    },
    UNSUPPORTED_URL: {
        "ar": "رابط غير مدعوم. استخدم TikTok أو YouTube أو Instagram أو Facebook.",
        "bn": "অসমর্থিত URL। TikTok, YouTube, Instagram বা Facebook ব্যবহার করুন।",
        "ca": "URL no compatible. Fes servir TikTok, YouTube, Instagram o Facebook.",
        "zh-Hans": "不支持的链接。请使用 TikTok、YouTube、Instagram 或 Facebook。",
        "zh-Hant": "不支援的連結。請使用 TikTok、YouTube、Instagram 或 Facebook。",
        "hr": "Nepodržani URL. Koristi TikTok, YouTube, Instagram ili Facebook.",
        "cs": "Nepodporovaná URL. Použijte TikTok, YouTube, Instagram nebo Facebook.",
        "da": "Ikke-understøttet URL. Brug TikTok, YouTube, Instagram eller Facebook.",
        "nl": "Niet-ondersteunde URL. Gebruik TikTok, YouTube, Instagram of Facebook.",
        "en-AU": UNSUPPORTED_URL,
        "en-CA": UNSUPPORTED_URL,
        "en-GB": UNSUPPORTED_URL,
        "en-US": UNSUPPORTED_URL,
        "fi": "URL-osoitetta ei tueta. Käytä TikTokia, YouTubea, Instagramia tai Facebookia.",
        "fr-FR": "URL non prise en charge. Utilisez TikTok, YouTube, Instagram ou Facebook.",
        "fr-CA": "URL non prise en charge. Utilisez TikTok, YouTube, Instagram ou Facebook.",
        "de": "Nicht unterstützte URL. Nutze TikTok, YouTube, Instagram oder Facebook.",
        "el": "Μη υποστηριζόμενο URL. Χρησιμοποίησε TikTok, YouTube, Instagram ή Facebook.",
        "gu": "અસમર્થિત URL. TikTok, YouTube, Instagram અથવા Facebook વાપરો.",
        "he": "כתובת לא נתמכת. השתמש ב-TikTok, YouTube, Instagram או Facebook.",
        "hi": "असमर्थित URL। TikTok, YouTube, Instagram या Facebook उपयोग करें।",
        "hu": "Nem támogatott URL. Használj TikTokot, YouTube-ot, Instagramot vagy Facebookot.",
        "id": "URL tidak didukung. Gunakan TikTok, YouTube, Instagram, atau Facebook.",
        "it": "URL non supportato. Usa TikTok, YouTube, Instagram o Facebook.",
        "ja": "対応していないURLです。TikTok、YouTube、Instagram、Facebookを使ってください。",
        "kn": "ಬೆಂಬಲಿಸದ URL. TikTok, YouTube, Instagram ಅಥವಾ Facebook ಬಳಸಿ.",
        "ko": "지원하지 않는 URL입니다. TikTok, YouTube, Instagram 또는 Facebook을 사용하세요.",
        "ms": "URL tidak disokong. Gunakan TikTok, YouTube, Instagram atau Facebook.",
        "ml": "പിന്തുണയില്ലാത്ത URL. TikTok, YouTube, Instagram അല്ലെങ്കിൽ Facebook ഉപയോഗിക്കുക.",
        "mr": "असमर्थित URL. TikTok, YouTube, Instagram किंवा Facebook वापरा.",
        "nb": "URL støttes ikke. Bruk TikTok, YouTube, Instagram eller Facebook.",
        "or": "ଅସମର୍ଥିତ URL। TikTok, YouTube, Instagram କିମ୍ବା Facebook ବ୍ୟବହାର କରନ୍ତୁ।",
        "pl": "Nieobsługiwany adres URL. Użyj TikToka, YouTube'a, Instagrama lub Facebooka.",
        "pt-BR": "URL não suportada. Use TikTok, YouTube, Instagram ou Facebook.",
        "pt-PT": "URL não suportado. Utilize TikTok, YouTube, Instagram ou Facebook.",
        "pa": "ਅਸਮਰਥਿਤ URL। TikTok, YouTube, Instagram ਜਾਂ Facebook ਵਰਤੋ।",
        "ro": "URL neacceptat. Folosește TikTok, YouTube, Instagram sau Facebook.",
        "ru": "Неподдерживаемая ссылка. Используйте TikTok, YouTube, Instagram или Facebook.",
        "sk": "Nepodporovaná URL. Použite TikTok, YouTube, Instagram alebo Facebook.",
        "sl": "Nepodprt URL. Uporabite TikTok, YouTube, Instagram ali Facebook.",
        "es-MX": "URL no compatible. Usa TikTok, YouTube, Instagram o Facebook.",
        "es-ES": "URL no compatible. Usa TikTok, YouTube, Instagram o Facebook.",
        "sv": "URL stöds inte. Använd TikTok, YouTube, Instagram eller Facebook.",
        "ta": "ஆதரிக்கப்படாத URL. TikTok, YouTube, Instagram அல்லது Facebook பயன்படுத்தவும்.",
        "te": "మద్దతు లేని URL. TikTok, YouTube, Instagram లేదా Facebook ఉపయోగించండి.",
        "th": "URL ที่ไม่รองรับ ใช้ TikTok, YouTube, Instagram หรือ Facebook",
        "tr": "Desteklenmeyen URL. TikTok, YouTube, Instagram veya Facebook kullanın.",
        "uk": "Непідтримуване посилання. Використовуйте TikTok, YouTube, Instagram або Facebook.",
        "ur": "غیر معاون URL۔ TikTok، YouTube، Instagram یا Facebook استعمال کریں۔",
        "vi": "URL không được hỗ trợ. Dùng TikTok, YouTube, Instagram hoặc Facebook.",
    },
    VIDEO_TOO_LONG: {
        "ar": "هذا الفيديو طويل جدًا لاستخراج وصفة.",
        "bn": "রেসিপি বের করার জন্য এই ভিডিওটি খুব দীর্ঘ।",
        "ca": "Aquest vídeo és massa llarg per extreure una recepta.",
        "zh-Hans": "这个视频太长，无法提取食谱。",
        "zh-Hant": "這個影片太長，無法擷取食譜。",
        "hr": "Ovaj je video predugačak za izdvajanje recepta.",
        "cs": "Toto video je příliš dlouhé na extrakci receptu.",
        "da": "Denne video er for lang til at hente en opskrift.",
        "nl": "Deze video is te lang om een recept te extraheren.",
        "en-AU": VIDEO_TOO_LONG,
        "en-CA": VIDEO_TOO_LONG,
        "en-GB": VIDEO_TOO_LONG,
        "en-US": VIDEO_TOO_LONG,
        "fi": "Tämä video on liian pitkä reseptin poimintaan.",
        "fr-FR": "Cette vidéo est trop longue pour en extraire une recette.",
        "fr-CA": "Cette vidéo est trop longue pour en extraire une recette.",
        "de": "Dieses Video ist zu lang, um ein Rezept zu extrahieren.",
        "el": "Αυτό το βίντεο είναι πολύ μεγάλο για εξαγωγή συνταγής.",
        "gu": "રેસીપી કાઢવા માટે આ વીડિયો ખૂબ લાંબો છે.",
        "he": "הסרטון הזה ארוך מדי לחילוץ מתכון.",
        "hi": "रेसिपी निकालने के लिए यह वीडियो बहुत लंबा है।",
        "hu": "Ez a videó túl hosszú a recept kinyeréséhez.",
        "id": "Video ini terlalu panjang untuk mengekstrak resep.",
        "it": "Questo video è troppo lungo per estrarre una ricetta.",
        "ja": "この動画は長すぎてレシピを抽出できません。",
        "kn": "ರೆಸಿಪಿ ಹೊರತೆಗೆಯಲು ಈ ವೀಡಿಯೊ ತುಂಬಾ ಉದ್ದವಾಗಿದೆ.",
        "ko": "이 영상은 레시피를 추출하기에 너무 깁니다.",
        "ms": "Video ini terlalu panjang untuk mengekstrak resipi.",
        "ml": "പാചകക്കുറിപ്പ് എടുക്കാൻ ഈ വീഡിയോ വളരെ നീളമുള്ളതാണ്.",
        "mr": "रेसिपी काढण्यासाठी हा व्हिडिओ खूप लांब आहे.",
        "nb": "Denne videoen er for lang til å hente en oppskrift.",
        "or": "ରେସିପି ବାହାର କରିବା ପାଇଁ ଏହି ଭିଡିଓ ଅତି ଲମ୍ବା।",
        "pl": "Ten film jest za długi, by wyodrębnić przepis.",
        "pt-BR": "Este vídeo é longo demais para extrair uma receita.",
        "pt-PT": "Este vídeo é demasiado longo para extrair uma receita.",
        "pa": "ਰੈਸਿਪੀ ਕੱਢਣ ਲਈ ਇਹ ਵੀਡੀਓ ਬਹੁਤ ਲੰਬੀ ਹੈ।",
        "ro": "Acest video este prea lung pentru a extrage o rețetă.",
        "ru": "Это видео слишком длинное, чтобы извлечь рецепт.",
        "sk": "Toto video je príliš dlhé na extrakciu receptu.",
        "sl": "Ta videoposnetek je predolg za izluščenje recepta.",
        "es-MX": "Este video es demasiado largo para extraer una receta.",
        "es-ES": "Este vídeo es demasiado largo para extraer una receta.",
        "sv": "Den här videon är för lång för att hämta ett recept.",
        "ta": "செய்முறை எடுக்க இந்த வீடியோ மிக நீளமானது.",
        "te": "రెసిపీ తీయడానికి ఈ వీడియో చాలా పొడవుగా ఉంది.",
        "th": "วิดีโอนี้ยาวเกินไปที่จะดึงสูตร",
        "tr": "Bu video tarif çıkarmak için çok uzun.",
        "uk": "Це відео надто довге, щоб витягти рецепт.",
        "ur": "ترکیب نکالنے کے لیے یہ ویڈیو بہت لمبی ہے۔",
        "vi": "Video này quá dài để trích xuất công thức.",
    },
    INCOMPLETE_CAROUSEL: {
        "ar": "عرض شرائح TikTok هذا غير مكتمل. جرّب رابطًا آخر أو فيديو وصفة كامل.",
        "bn": "এই TikTok ক্যারাউজেল অসম্পূর্ণ। অন্য লিংক বা পূর্ণ রেসিপি ভিডিও চেষ্টা করুন।",
        "ca": "Aquest carrusel de TikTok està incomplet. Prova un altre enllaç o un vídeo de recepta complet.",
        "zh-Hans": "这个 TikTok 轮播不完整。请尝试其他链接或完整食谱视频。",
        "zh-Hant": "這個 TikTok 輪播不完整。請嘗試其他連結或完整食譜影片。",
        "hr": "Ovaj TikTok carousel nije potpun. Pokušaj drugi link ili cijeli video recepta.",
        "cs": "Tento TikTok karusel je neúplný. Zkuste jiný odkaz nebo celé video receptu.",
        "da": "Denne TikTok-karrusel er ufuldstændig. Prøv et andet link eller en fuld opskriftsvideo.",
        "nl": "Deze TikTok-carrousel is incompleet. Probeer een andere link of een volledige receptvideo.",
        "en-AU": INCOMPLETE_CAROUSEL,
        "en-CA": INCOMPLETE_CAROUSEL,
        "en-GB": INCOMPLETE_CAROUSEL,
        "en-US": INCOMPLETE_CAROUSEL,
        "fi": "Tämä TikTok-karuselli on epätäydellinen. Kokeile toista linkkiä tai täyttä reseptivideota.",
        "fr-FR": "Ce carrousel TikTok est incomplet. Essayez un autre lien ou une vidéo de recette complète.",
        "fr-CA": "Ce carrousel TikTok est incomplet. Essayez un autre lien ou une vidéo de recette complète.",
        "de": "Dieses TikTok-Karussell ist unvollständig. Versuche einen anderen Link oder ein vollständiges Rezeptvideo.",
        "el": "Αυτό το καρουζέλ TikTok είναι ημιτελές. Δοκίμασε άλλο σύνδεσμο ή πλήρες βίντεο συνταγής.",
        "gu": "આ TikTok કેરોઝલ અપૂર્ણ છે. બીજી લિંક અથવા સંપૂર્ણ રેસીપી વીડિયો અજમાવો.",
        "he": "קרוסלת TikTok זו אינה שלמה. נסה קישור אחר או סרטון מתכון מלא.",
        "hi": "यह TikTok कैरोसेल अधूरा है। कोई अन्य लिंक या पूरी रेसिपी वीडियो आज़माएँ।",
        "hu": "Ez a TikTok-körkép hiányos. Próbálj másik linket vagy egy teljes receptvideót.",
        "id": "Karousel TikTok ini tidak lengkap. Coba tautan lain atau video resep lengkap.",
        "it": "Questo carosello TikTok è incompleto. Prova un altro link o un video ricetta completo.",
        "ja": "このTikTokカルーセルは不完全です。別のリンクか完全なレシピ動画を試してください。",
        "kn": "ಈ TikTok ಕರೌಸೆಲ್ ಅಪೂರ್ಣವಾಗಿದೆ. ಬೇರೆ ಲಿಂಕ್ ಅಥವಾ ಪೂರ್ಣ ರೆಸಿಪಿ ವೀಡಿಯೊ ಪ್ರಯತ್ನಿಸಿ.",
        "ko": "이 TikTok 캐러셀이 불완전합니다. 다른 링크나 전체 레시피 영상을 시도하세요.",
        "ms": "Karusel TikTok ini tidak lengkap. Cuba pautan lain atau video resipi penuh.",
        "ml": "ഈ TikTok കറൗസൽ അപൂർണ്ണമാണ്. മറ്റൊരു ലിങ്കോ പൂർണ്ണ പാചക വീഡിയോയോ ശ്രമിക്കുക.",
        "mr": "हा TikTok कॅरोसेल अपूर्ण आहे. दुसरी लिंक किंवा पूर्ण रेसिपी व्हिडिओ वापरून पहा.",
        "nb": "Denne TikTok-karusellen er ufullstendig. Prøv en annen lenke eller en full oppskriftsvideo.",
        "or": "ଏହି TikTok କ୍ୟାରୋଜେଲ୍ ଅସମ୍ପୂର୍ଣ୍ଣ। ଅନ୍ୟ ଲିଙ୍କ୍ କିମ୍ବା ପୂରା ରେସିପି ଭିଡିଓ ଚେଷ୍ଟା କରନ୍ତୁ।",
        "pl": "Ten karuzela TikTok jest niekompletna. Spróbuj innego linku lub pełnego filmu z przepisem.",
        "pt-BR": "Este carrossel do TikTok está incompleto. Tente outro link ou um vídeo de receita completo.",
        "pt-PT": "Este carrossel do TikTok está incompleto. Tente outra ligação ou um vídeo de receita completo.",
        "pa": "ਇਹ TikTok ਕੈਰੋਸੈਲ ਅਧੂਰਾ ਹੈ। ਕੋਈ ਹੋਰ ਲਿੰਕ ਜਾਂ ਪੂਰੀ ਰੈਸਿਪੀ ਵੀਡੀਓ ਅਜ਼ਮਾਓ।",
        "ro": "Acest carusel TikTok este incomplet. Încearcă alt link sau un video complet cu rețeta.",
        "ru": "Эта карусель TikTok неполная. Попробуйте другую ссылку или полное видео с рецептом.",
        "sk": "Tento TikTok karusel je neúplný. Skúste iný odkaz alebo celé video receptu.",
        "sl": "Ta TikTok vrtiljak je nepopoln. Poskusite drugo povezavo ali celoten video recepta.",
        "es-MX": "Este carrusel de TikTok está incompleto. Prueba otro enlace o un video de receta completo.",
        "es-ES": "Este carrusel de TikTok está incompleto. Prueba otro enlace o un vídeo de receta completo.",
        "sv": "Den här TikTok-karusellen är ofullständig. Prova en annan länk eller en komplett receptvideo.",
        "ta": "இந்த TikTok கரோசல் முழுமையற்றது. வேறு இணைப்பு அல்லது முழு செய்முறை வீடியோவை முயற்சிக்கவும்.",
        "te": "ఈ TikTok కరౌజెల్ అసంపూర్ణం. మరో లింక్ లేదా పూర్తి రెసిపీ వీడియో ప్రయత్నించండి.",
        "th": "แคโรเซล TikTok นี้ไม่สมบูรณ์ ลองลิงก์อื่นหรือวิดีโอสูตรเต็ม",
        "tr": "Bu TikTok karuseli eksik. Başka bir bağlantı veya tam tarif videosu deneyin.",
        "uk": "Ця карусель TikTok неповна. Спробуйте інше посилання або повне відео з рецептом.",
        "ur": "یہ TikTok کیروسل نامکمل ہے۔ دوسرا لنک یا مکمل ترکیب والی ویڈیو آزمائیں۔",
        "vi": "Băng chuyền TikTok này chưa đầy đủ. Thử liên kết khác hoặc video công thức đầy đủ.",
    },
    EXTRACTION_RETRYABLE: {
        "ar": "فشلت عملية الاستخراج مؤقتًا. أعد محاولة الاستيراد.",
        "bn": "এক্সট্র্যাকশন সাময়িকভাবে ব্যর্থ হয়েছে। আবার ইমপোর্ট করুন।",
        "ca": "L'extracció ha fallat temporalment. Torna a provar la importació.",
        "zh-Hans": "提取暂时失败。请重试导入。",
        "zh-Hant": "擷取暫時失敗。請重試匯入。",
        "hr": "Izdvajanje je privremeno neuspjelo. Pokušaj ponovno uvesti.",
        "cs": "Extrakce dočasně selhala. Zkuste import znovu.",
        "da": "Udtrækningen mislykkedes midlertidigt. Prøv importen igen.",
        "nl": "Extractie is tijdelijk mislukt. Probeer de import opnieuw.",
        "en-AU": EXTRACTION_RETRYABLE,
        "en-CA": EXTRACTION_RETRYABLE,
        "en-GB": EXTRACTION_RETRYABLE,
        "en-US": EXTRACTION_RETRYABLE,
        "fi": "Poiminta epäonnistui tilapäisesti. Yritä tuontia uudelleen.",
        "fr-FR": "L'extraction a temporairement échoué. Réessayez l'import.",
        "fr-CA": "L'extraction a temporairement échoué. Réessayez l'importation.",
        "de": "Die Extraktion ist vorübergehend fehlgeschlagen. Import erneut versuchen.",
        "el": "Η εξαγωγή απέτυχε προσωρινά. Δοκίμασε ξανά την εισαγωγή.",
        "gu": "એક્સટ્રેક્શન અસ્થાયી રૂપે નિષ્ફળ થયું. આયાત ફરી પ્રયાસ કરો.",
        "he": "החילוץ נכשל זמנית. נסה לייבא שוב.",
        "hi": "एक्सट्रैक्शन अस्थायी रूप से विफल रहा। आयात फिर से आज़माएँ।",
        "hu": "A kinyerés átmenetileg sikertelen. Próbáld újra az importot.",
        "id": "Ekstraksi sementara gagal. Coba impor lagi.",
        "it": "Estrazione temporaneamente non riuscita. Riprova l'importazione.",
        "ja": "抽出が一時的に失敗しました。もう一度インポートしてください。",
        "kn": "ಹೊರತೆಗೆಯುವಿಕೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ವಿಫಲವಾಯಿತು. ಆಮದನ್ನು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        "ko": "추출이 일시적으로 실패했습니다. 가져오기를 다시 시도하세요.",
        "ms": "Pengekstrakan gagal buat sementara. Cuba import semula.",
        "ml": "എക്സ്ട്രാക്ഷൻ താൽക്കാലികമായി പരാജയപ്പെട്ടു. ഇമ്പോർട്ട് വീണ്ടും ശ്രമിക്കുക.",
        "mr": "एक्सट्रॅक्शन तात्पुरते अयशस्वी झाले. आयात पुन्हा करा.",
        "nb": "Uthenting midlertidig mislyktes. Prøv importen på nytt.",
        "or": "ଏକ୍ସଟ୍ରାକ୍ସନ୍ ସାମୟିକ ଭାବେ ବିଫଳ। ଇମ୍ପୋର୍ଟ ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ।",
        "pl": "Wyodrębnianie tymczasowo nie powiodło się. Spróbuj ponownie zaimportować.",
        "pt-BR": "A extração falhou temporariamente. Tente importar de novo.",
        "pt-PT": "A extração falhou temporariamente. Tente importar novamente.",
        "pa": "ਐਕਸਟ੍ਰੈਕਸ਼ਨ ਅਸਥਾਈ ਤੌਰ ’ਤੇ ਫੇਲ੍ਹ ਹੋਈ। ਆਯਾਤ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "ro": "Extracția a eșuat temporar. Reîncearcă importul.",
        "ru": "Извлечение временно не удалось. Повторите импорт.",
        "sk": "Extrakcia dočasne zlyhala. Skúste import znova.",
        "sl": "Izluščenje je začasno spodletelo. Poskusite uvoz znova.",
        "es-MX": "La extracción falló temporalmente. Vuelve a intentar la importación.",
        "es-ES": "La extracción falló temporalmente. Vuelve a intentar la importación.",
        "sv": "Hämtningen misslyckades tillfälligt. Försök importera igen.",
        "ta": "பிரித்தெடுப்பு தற்காலிகமாக தோல்வியடைந்தது. இறக்குமதியை மீண்டும் முயற்சிக்கவும்.",
        "te": "వెలికితీత తాత్కాలికంగా విఫలమైంది. దిగుమతిని మళ్లీ ప్రయత్నించండి.",
        "th": "การดึงข้อมูลล้มเหลวชั่วคราว ลองนำเข้าอีกครั้ง",
        "tr": "Çıkarma geçici olarak başarısız oldu. İçe aktarmayı yeniden deneyin.",
        "uk": "Витяг тимчасово не вдався. Повторіть імпорт.",
        "ur": "نکالنا عارضی طور پر ناکام رہا۔ درآمد دوبارہ آزمائیں۔",
        "vi": "Trích xuất tạm thời thất bại. Thử nhập lại.",
    },
    NO_RECIPE_TEXT: {
        "ar": "لم يُعثر على نص وصفة صالح في هذا الفيديو.",
        "bn": "এই ভিডিওতে ব্যবহারযোগ্য রেসিপি লেখা পাওয়া যায়নি।",
        "ca": "No s'ha trobat text de recepta útil en aquest vídeo.",
        "zh-Hans": "在这个视频中未找到可用的食谱文本。",
        "zh-Hant": "在這個影片中找不到可用的食譜文字。",
        "hr": "U ovom videu nije pronađen upotrebljiv tekst recepta.",
        "cs": "V tomto videu nebyl nalezen použitelný text receptu.",
        "da": "Ingen brugbar opskriftstekst fundet i denne video.",
        "nl": "Geen bruikbare recepttekst gevonden in deze video.",
        "en-AU": NO_RECIPE_TEXT,
        "en-CA": NO_RECIPE_TEXT,
        "en-GB": NO_RECIPE_TEXT,
        "en-US": NO_RECIPE_TEXT,
        "fi": "Tästä videosta ei löytynyt käyttökelpoista reseptitekstiä.",
        "fr-FR": "Aucun texte de recette exploitable trouvé dans cette vidéo.",
        "fr-CA": "Aucun texte de recette exploitable trouvé dans cette vidéo.",
        "de": "In diesem Video wurde kein brauchbarer Rezepttext gefunden.",
        "el": "Δεν βρέθηκε χρήσιμο κείμενο συνταγής σε αυτό το βίντεο.",
        "gu": "આ વીડિયામાં ઉપયોગી રેસીપી લખાણ મળ્યું નથી.",
        "he": "לא נמצא טקסט מתכון שמיש בסרטון הזה.",
        "hi": "इस वीडियो में उपयोगी रेसिपी पाठ नहीं मिला।",
        "hu": "Ebben a videóban nem található használható receptszöveg.",
        "id": "Tidak ditemukan teks resep yang dapat digunakan di video ini.",
        "it": "Nessun testo di ricetta utilizzabile trovato in questo video.",
        "ja": "この動画に使えるレシピテキストが見つかりませんでした。",
        "kn": "ಈ ವೀಡಿಯೊದಲ್ಲಿ ಬಳಸಬಹುದಾದ ರೆಸಿಪಿ ಪಠ್ಯ ಕಂಡುಬಂದಿಲ್ಲ.",
        "ko": "이 영상에서 사용할 수 있는 레시피 텍스트를 찾지 못했습니다.",
        "ms": "Tiada teks resipi yang berguna ditemui dalam video ini.",
        "ml": "ഈ വീഡിയോയിൽ ഉപയോഗയോഗ്യമായ പാചക വാചകം കണ്ടെത്തിയില്ല.",
        "mr": "या व्हिडिओमध्ये वापरण्यायोग्य रेसिपी मजकूर सापडला नाही.",
        "nb": "Ingen brukbar oppskriftstekst funnet i denne videoen.",
        "or": "ଏହି ଭିଡିଓରେ ବ୍ୟବହାରଯୋଗ୍ୟ ରେସିପି ପାଠ ମିଳିଲା ନାହିଁ।",
        "pl": "W tym filmie nie znaleziono użytecznego tekstu przepisu.",
        "pt-BR": "Nenhum texto de receita utilizável encontrado neste vídeo.",
        "pt-PT": "Nenhum texto de receita utilizável encontrado neste vídeo.",
        "pa": "ਇਸ ਵੀਡੀਓ ਵਿੱਚ ਵਰਤੋਂਯੋਗ ਰੈਸਿਪੀ ਲਿਖਤ ਨਹੀਂ ਮਿਲੀ।",
        "ro": "Nu s-a găsit text de rețetă util în acest video.",
        "ru": "В этом видео не найден пригодный текст рецепта.",
        "sk": "V tomto videu sa nenašiel použiteľný text receptu.",
        "sl": "V tem videoposnetku ni bilo najdenega uporabnega besedila recepta.",
        "es-MX": "No se encontró texto de receta útil en este video.",
        "es-ES": "No se encontró texto de receta útil en este vídeo.",
        "sv": "Ingen användbar recepttext hittades i den här videon.",
        "ta": "இந்த வீடியோவில் பயனுள்ள செய்முறை உரை கிடைக்கவில்லை.",
        "te": "ఈ వీడియోలో ఉపయోగపడే రెసిపీ టెక్స్ట్ కనబడలేదు.",
        "th": "ไม่พบข้อความสูตรที่ใช้ได้ในวิดีโอนี้",
        "tr": "Bu videoda kullanılabilir bir tarif metni bulunamadı.",
        "uk": "У цьому відео не знайдено придатного тексту рецепта.",
        "ur": "اس ویڈیو میں قابلِ استعمال ترکیب کا متن نہیں ملا۔",
        "vi": "Không tìm thấy văn bản công thức dùng được trong video này.",
    },
    SOURCE_BOUND: {
        "ar": "مصدر هذه الوصفة كبير جدًا للمعالجة.",
        "bn": "এই রেসিপির উৎস প্রক্রিয়া করার জন্য খুব বড়।",
        "ca": "Aquesta font de recepta és massa gran per processar-la.",
        "zh-Hans": "此食谱来源过大，无法处理。",
        "zh-Hant": "此食譜來源過大，無法處理。",
        "hr": "Izvor ovog recepta je prevelik za obradu.",
        "cs": "Tento zdroj receptu je příliš velký ke zpracování.",
        "da": "Denne opskriftskilde er for stor til at behandle.",
        "nl": "Deze receptbron is te groot om te verwerken.",
        "en-AU": SOURCE_BOUND,
        "en-CA": SOURCE_BOUND,
        "en-GB": SOURCE_BOUND,
        "en-US": SOURCE_BOUND,
        "fi": "Tämä reseptilähde on liian suuri käsiteltäväksi.",
        "fr-FR": "Cette source de recette est trop volumineuse à traiter.",
        "fr-CA": "Cette source de recette est trop volumineuse à traiter.",
        "de": "Diese Rezeptquelle ist zu groß für die Verarbeitung.",
        "el": "Αυτή η πηγή συνταγής είναι πολύ μεγάλη για επεξεργασία.",
        "gu": "આ રેસીપી સ્ત્રોત પ્રક્રિયા કરવા માટે ખૂબ મોટો છે.",
        "he": "מקור המתכון הזה גדול מדי לעיבוד.",
        "hi": "यह रेसिपी स्रोत प्रोसेस करने के लिए बहुत बड़ा है।",
        "hu": "Ez a receptforrás túl nagy a feldolgozáshoz.",
        "id": "Sumber resep ini terlalu besar untuk diproses.",
        "it": "Questa fonte di ricetta è troppo grande da elaborare.",
        "ja": "このレシピの情報が大きすぎて処理できません。",
        "kn": "ಈ ರೆಸಿಪಿ ಮೂಲವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲು ತುಂಬಾ ದೊಡ್ಡದಾಗಿದೆ.",
        "ko": "이 레시피 소스가 너무 커서 처리할 수 없습니다.",
        "ms": "Sumber resipi ini terlalu besar untuk diproses.",
        "ml": "ഈ പാചക ഉറവിടം പ്രോസസ് ചെയ്യാൻ വളരെ വലുതാണ്.",
        "mr": "हा रेसिपी स्रोत प्रक्रिया करण्यासाठी खूप मोठा आहे.",
        "nb": "Denne oppskriftskilden er for stor til å behandle.",
        "or": "ଏହି ରେସିପି ଉତ୍ସ ପ୍ରକ୍ରିୟା ପାଇଁ ଅତି ବଡ଼।",
        "pl": "To źródło przepisu jest zbyt duże do przetworzenia.",
        "pt-BR": "Esta fonte de receita é grande demais para processar.",
        "pt-PT": "Esta fonte de receita é demasiado grande para processar.",
        "pa": "ਇਹ ਰੈਸਿਪੀ ਸਰੋਤ ਪ੍ਰੋਸੈਸ ਕਰਨ ਲਈ ਬਹੁਤ ਵੱਡਾ ਹੈ।",
        "ro": "Această sursă de rețetă este prea mare pentru a fi procesată.",
        "ru": "Этот источник рецепта слишком большой для обработки.",
        "sk": "Tento zdroj receptu je príliš veľký na spracovanie.",
        "sl": "Ta vir recepta je prevelik za obdelavo.",
        "es-MX": "Esta fuente de receta es demasiado grande para procesarla.",
        "es-ES": "Esta fuente de receta es demasiado grande para procesarla.",
        "sv": "Den här receptkällan är för stor att bearbeta.",
        "ta": "இந்த செய்முறை மூலம் செயலாக்க மிகப் பெரியது.",
        "te": "ఈ రెసిపీ మూలం ప్రాసెస్ చేయడానికి చాలా పెద్దది.",
        "th": "แหล่งสูตรนี้ใหญ่เกินไปที่จะประมวลผล",
        "tr": "Bu tarif kaynağı işlenemeyecek kadar büyük.",
        "uk": "Це джерело рецепта надто велике для обробки.",
        "ur": "اس ترکیب کا ماخذ پروسیس کرنے کے لیے بہت بڑا ہے۔",
        "vi": "Nguồn công thức này quá lớn để xử lý.",
    },
    STALE_JOB: {
        "ar": "انتهت صلاحية المهمة قبل الإكمال. أعد محاولة الاستيراد.",
        "bn": "সম্পূর্ণ হওয়ার আগে কাজের মেয়াদ শেষ। আবার ইমপোর্ট করুন।",
        "ca": "La tasca ha caducat abans de completar-se. Torna a provar la importació.",
        "zh-Hans": "任务在完成前已过期。请重试导入。",
        "zh-Hant": "工作在完成前已過期。請重試匯入。",
        "hr": "Zadatak je istekao prije dovršetka. Pokušaj ponovno uvesti.",
        "cs": "Úloha vypršela před dokončením. Zkuste import znovu.",
        "da": "Jobbet udløb før færdiggørelse. Prøv importen igen.",
        "nl": "Taak verlopen vóór afronding. Probeer de import opnieuw.",
        "en-AU": STALE_JOB,
        "en-CA": STALE_JOB,
        "en-GB": STALE_JOB,
        "en-US": STALE_JOB,
        "fi": "Työ vanhentui ennen valmistumista. Yritä tuontia uudelleen.",
        "fr-FR": "La tâche a expiré avant d'être terminée. Réessayez l'import.",
        "fr-CA": "La tâche a expiré avant d'être terminée. Réessayez l'importation.",
        "de": "Auftrag vor Abschluss abgelaufen. Import erneut versuchen.",
        "el": "Η εργασία έληξε πριν ολοκληρωθεί. Δοκίμασε ξανά την εισαγωγή.",
        "gu": "પૂર્ણ થાય તે પહેલાં જોબ સમાપ્ત થઈ. આયાત ફરી પ્રયાસ કરો.",
        "he": "המשימה פגה לפני שהושלמה. נסה לייבא שוב.",
        "hi": "पूरा होने से पहले जॉब समाप्त हो गई। आयात फिर से आज़माएँ।",
        "hu": "A feladat lejárt a befejezés előtt. Próbáld újra az importot.",
        "id": "Pekerjaan kedaluwarsa sebelum selesai. Coba impor lagi.",
        "it": "Processo scaduto prima del completamento. Riprova l'importazione.",
        "ja": "完了前にジョブの期限が切れました。もう一度インポートしてください。",
        "kn": "ಪೂರ್ಣಗೊಳ್ಳುವ ಮೊದಲು ಜಾಬ್ ಅವಧಿ ಮುಗಿಯಿತು. ಆಮದನ್ನು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
        "ko": "완료 전에 작업이 만료되었습니다. 가져오기를 다시 시도하세요.",
        "ms": "Tugas tamat tempoh sebelum selesai. Cuba import semula.",
        "ml": "പൂർത്തിയാകുന്നതിന് മുമ്പ് ജോബ് കാലഹരണപ്പെട്ടു. ഇമ്പോർട്ട് വീണ്ടും ശ്രമിക്കുക.",
        "mr": "पूर्ण होण्यापूर्वी जॉब कालबाह्य झाली. आयात पुन्हा करा.",
        "nb": "Jobben utløp før den ble fullført. Prøv importen på nytt.",
        "or": "ସମ୍ପୂର୍ଣ୍ଣ ହେବା ପୂର୍ବରୁ ଜବ୍ ସମାପ୍ତ। ଇମ୍ପୋର୍ଟ ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ।",
        "pl": "Zadanie wygasło przed ukończeniem. Spróbuj ponownie zaimportować.",
        "pt-BR": "A tarefa expirou antes de concluir. Tente importar de novo.",
        "pt-PT": "A tarefa expirou antes de concluir. Tente importar novamente.",
        "pa": "ਪੂਰਾ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਜੌਬ ਖਤਮ ਹੋ ਗਈ। ਆਯਾਤ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
        "ro": "Sarcina a expirat înainte de finalizare. Reîncearcă importul.",
        "ru": "Задача истекла до завершения. Повторите импорт.",
        "sk": "Úloha vypršala pred dokončením. Skúste import znova.",
        "sl": "Naloga je potekla pred dokončanjem. Poskusite uvoz znova.",
        "es-MX": "El trabajo caducó antes de completarse. Vuelve a intentar la importación.",
        "es-ES": "El trabajo caducó antes de completarse. Vuelve a intentar la importación.",
        "sv": "Jobbet gick ut innan det slutfördes. Försök importera igen.",
        "ta": "முடிவதற்கு முன் பணி காலாவதியானது. இறக்குமதியை மீண்டும் முயற்சிக்கவும்.",
        "te": "పూర్తయ్యేలోపు జాబ్ గడువు ముగిసింది. దిగుమతిని మళ్లీ ప్రయత్నించండి.",
        "th": "งานหมดอายุก่อนเสร็จ ลองนำเข้าอีกครั้ง",
        "tr": "İş tamamlanmadan süresi doldu. İçe aktarmayı yeniden deneyin.",
        "uk": "Завдання закінчилося до завершення. Повторіть імпорт.",
        "ur": "مکمل ہونے سے پہلے جاب ختم ہو گئی۔ درآمد دوبارہ آزمائیں۔",
        "vi": "Công việc hết hạn trước khi hoàn tất. Thử nhập lại.",
    },
    TRANSLATION_MISSING: {
        "ar": "لم يتم العثور على الوصفة للترجمة.",
        "bn": "অনুবাদের জন্য রেসিপি পাওয়া যায়নি।",
        "ca": "No s'ha trobat la recepta per traduir.",
        "zh-Hans": "未找到要翻译的食谱。",
        "zh-Hant": "找不到要翻譯的食譜。",
        "hr": "Recept za prijevod nije pronađen.",
        "cs": "Recept k překladu nebyl nalezen.",
        "da": "Opskrift til oversættelse blev ikke fundet.",
        "nl": "Recept voor vertaling niet gevonden.",
        "en-AU": TRANSLATION_MISSING,
        "en-CA": TRANSLATION_MISSING,
        "en-GB": TRANSLATION_MISSING,
        "en-US": TRANSLATION_MISSING,
        "fi": "Käännettävää reseptiä ei löytynyt.",
        "fr-FR": "Recette introuvable pour la traduction.",
        "fr-CA": "Recette introuvable pour la traduction.",
        "de": "Rezept für die Übersetzung nicht gefunden.",
        "el": "Η συνταγή για μετάφραση δεν βρέθηκε.",
        "gu": "અનુવાદ માટે રેસીપી મળી નથી.",
        "he": "המתכון לתרגום לא נמצא.",
        "hi": "अनुवाद के लिए रेसिपी नहीं मिली।",
        "hu": "A fordítandó recept nem található.",
        "id": "Resep untuk terjemahan tidak ditemukan.",
        "it": "Ricetta non trovata per la traduzione.",
        "ja": "翻訳するレシピが見つかりませんでした。",
        "kn": "ಅನುವಾದಕ್ಕೆ ರೆಸಿಪಿ ಕಂಡುಬಂದಿಲ್ಲ.",
        "ko": "번역할 레시피를 찾지 못했습니다.",
        "ms": "Resipi untuk terjemahan tidak ditemui.",
        "ml": "വിവർത്തനത്തിനുള്ള പാചകക്കുറിപ്പ് കണ്ടെത്തിയില്ല.",
        "mr": "भाषांतरासाठी रेसिपी सापडली नाही.",
        "nb": "Oppskrift for oversettelse ble ikke funnet.",
        "or": "ଅନୁବାଦ ପାଇଁ ରେସିପି ମିଳିଲା ନାହିଁ।",
        "pl": "Nie znaleziono przepisu do tłumaczenia.",
        "pt-BR": "Receita não encontrada para tradução.",
        "pt-PT": "Receita não encontrada para tradução.",
        "pa": "ਅਨੁਵਾਦ ਲਈ ਰੈਸਿਪੀ ਨਹੀਂ ਮਿਲੀ।",
        "ro": "Rețeta pentru traducere nu a fost găsită.",
        "ru": "Рецепт для перевода не найден.",
        "sk": "Recept na preklad sa nenašiel.",
        "sl": "Recepta za prevod ni bilo mogoče najti.",
        "es-MX": "No se encontró la receta para traducir.",
        "es-ES": "No se encontró la receta para traducir.",
        "sv": "Receptet för översättning hittades inte.",
        "ta": "மொழிபெயர்ப்புக்கான செய்முறை கிடைக்கவில்லை.",
        "te": "అనువాదం కోసం రెసిపీ కనబడలేదు.",
        "th": "ไม่พบสูตรสำหรับแปล",
        "tr": "Çeviri için tarif bulunamadı.",
        "uk": "Рецепт для перекладу не знайдено.",
        "ur": "ترجمے کے لیے ترکیب نہیں ملی۔",
        "vi": "Không tìm thấy công thức để dịch.",
    },
}


def _assert_complete() -> None:
    for message, translations in _MESSAGES.items():
        missing = set(SUPPORTED_LANGUAGE_CODES) - set(translations)
        if missing:
            raise RuntimeError(f"job error missing locales for {message!r}: {sorted(missing)}")


_assert_complete()


def canonicalize_job_error(message: str) -> str:
    """Map provider / legacy strings onto a stable English user-facing message."""
    text = (message or "").strip()
    if not text:
        return EXTRACTION_RETRYABLE
    if text in _MESSAGES:
        return text
    if text.startswith("Video too long ("):
        return VIDEO_TOO_LONG
    if text.startswith("Incomplete TikTok carousel:") or text.startswith("TikTok video evidence incomplete:"):
        return INCOMPLETE_CAROUSEL
    if text.startswith("No usable recipe text found"):
        return NO_RECIPE_TEXT
    if text.startswith("Recipe source text exceeds supported bound"):
        return SOURCE_BOUND
    if text.startswith("Unsupported URL."):
        return UNSUPPORTED_URL
    if text.startswith("Recipe not found for translation"):
        return TRANSLATION_MISSING
    if text.startswith("Recipe model refused") or text.startswith("Recipe model returned"):
        return EXTRACTION_RETRYABLE
    if text.startswith("Recipe output failed validation") or text.startswith(
        "Translated recipe output failed validation"
    ):
        return EXTRACTION_RETRYABLE
    if text == "Job expired before completion. Retry the import.":
        return STALE_JOB
    # Legacy English copy still stored on older jobs.
    legacy = {
        "Could not determine a recipe from this video.": RECIPE_UNDETERMINED,
        "Could not extract a complete recipe from this video.": RECIPE_INCOMPLETE,
        "Recipe link in bio. Open the creator profile bio for the full recipe.": LINK_IN_BIO,
        "Extraction temporarily failed. Retry the import.": EXTRACTION_RETRYABLE,
        "Unsupported URL. Use TikTok, YouTube, Instagram or Facebook.": UNSUPPORTED_URL,
    }
    return legacy.get(text, EXTRACTION_RETRYABLE)


def localize_job_error(message: str | None, language_code: str | None) -> str | None:
    if message is None:
        return None
    canonical = canonicalize_job_error(message)
    code = normalize_language(language_code)
    return _MESSAGES[canonical][code]


def job_error_code(message: str | None) -> str | None:
    if not message:
        return None
    return ERROR_CODES.get(canonicalize_job_error(message))
