http:
  routers:
    coolify-ui-https:
      rule: "Host(`coolify.51-255-43-100.sslip.io`)"
      entryPoints:
        - https
      service: coolify-ui
      tls:
        certResolver: letsencrypt
    coolify-ui-http:
      rule: "Host(`coolify.51-255-43-100.sslip.io`)"
      entryPoints:
        - http
      middlewares:
        - coolify-ui-redirect
      service: coolify-ui
  middlewares:
    coolify-ui-redirect:
      redirectScheme:
        scheme: https
  services:
    coolify-ui:
      loadBalancer:
        servers:
          - url: "http://coolify:8080"
