---
title: ReciApp Ops
theme: dark
color: slate
headerStyle: clean
hideVersion: true
target: _blank
language: es
showStats: true
layout:
  Ops:
    style: row
    columns: 4
  API:
    style: row
    columns: 4
  Infra:
    style: row
    columns: 3
